# Discussion

<!-- Big summary/important statement for the science -->
Here, we have provided a method for exploring the incorporation of dietary 
starches into the mineral matrix of a dental calculus biofilm model. Our results show
that a very low proportion of the starches exposed to the biofilm during growth are
retained in the mineral matrix, and that the size of the starch granules
may affect the likeliness of incorporation. The proportions of starch granules 
(of all sizes) present in the extracted samples  were similar across all treatments
(`r paste(min(perc$total), max(perc$total), sep = " to ")`), 
despite large differences in absolute granule counts between wheat 
(`r format(count_sol$total[4], big.mark = ",")`) 
and potato
(`r format(count_sol$total[3], big.mark = ",")`)
solutions.  
The absolute counts, however, differed more visibly between treatments and was
proportional with the total count of granules in the treatment solutions. Wheat 
and mixed solutions had the highest absolute mean count of starch granules, and 
also had the highest absolute mean count of starch granules extracted from the 
dental calculus
(Tables \@ref(tab:solution-count-tbl) and \@ref(tab:sample-count-tbl)).
This suggests that the starches that are more frequently consumed will be present
in higher quantities in the dental calculus, at least prior to inhumation and 
degradation in the burial environment; although, starch availability is unlikely
to be a main factor in starch incorporation. 
Despite the low proportion of granules recovered from the model calculus 
(`r paste(min(perc$total), max(perc$total), sep = " to ")`),
the absolute counts were still substantially greater than counts recovered from 
archaeological remains 
[@trompDietaryNondietary2015; @trompEDTACalculus2017; @wesolowskiEvaluatingMicrofossilContent2010].

<!--
Given the low proportion of starch granule retention in our dental calculus model,
and the limited difference between treatments, we can conjecture that starch 
availability is not a main factor in starch incorporation. While there was a
proportional incorporation, i.e. more granules in the solution led to more granules
in the calculus, the difference between solutions [a number/percentage] was of a
higher magnitude than the difference between samples <!-- a number/percentage-->

<!-- although this study extrapolated counts to full sample content, which is
rarely done in archaeological studies-->

<!-- Scientific findings as extension of previous work -->
Previous research conducted on dental calculus from contemporary humans and non-human
primates suggest a high level of stochasticity involved in the retention of 
starch granules in dental calculus, and that starch granules extracted from dental 
calculus are underrepresented with regard
to actual starch intake, which is consistent with our findings (illustrated by high
standard deviations and low proportional incorporation).
Leonard and colleagues [-@leonardDentalCalculus2015] found individual
calculus samples to be a poor predictor of diet in a population, as many of the 
consumed plants were missing from some individual samples, but were present in others.   
Power and colleagues [-@powerChimpCalculus2015] 
presented similar findings in non-human primates, where phytoliths were more
representative of individual diets than starch granules, and plants that 
produce predominantly larger starch (10-20 $\mu$m) granules were over-represented.
Both studies concluded that the dietary breadth of a population can
be captured in a sufficiently large sample, but interpretations on individual diets
from microremains in dental calculus is tenuous, at best 
[@leonardDentalCalculus2015; @powerChimpCalculus2015].

<!-- concentrations of solutions vs. starches in a mouthful of food 
starches in a potato, etc. 
Contact Steph -->

<!-- secondary findings -->

We have also shown that the size of the starch granules influences the likelihood
of incorporation into the calculus. Starch granules larger than 20 $\mu$m in 
diameter were underrepresented in the calculus samples compared to the original 
starch solutions, an effect that was consistent across all three treatments, 
while medium granules (10 -- 20 $\mu$m) were often over-represented
(Table \@ref(tab:sample-prop-tbl), 
and Figures \@ref(fig:sep-plot) and \@ref(fig:mix-plot)).
This was especially true for the potato starches, which can reach up to 100 $\mu$m
in diameter, whereas wheat generally only reach up to 35 $\mu$m 
[@gismondiStarchGranulesData2019; @haslamDecompositionStarch2004].
This is consistent with the findings by Power and collagues [-@powerChimpCalculus2015]
mentioned previously, which found that the larger (defined as around 10 -- 20 $\mu$m) 
granule-producing plants were overrepresented; although, the representation of granules 
larger than 20 $\mu$m in that study is unclear. Since those results were obtained
on a modern population of chimps that were only buried for a short period of time, 
degradation was likely limited [@powerChimpCalculus2015]. The taphonomy of
starch granules has been addressed previously, and depends on burial environment
(pH, temperature, microorganisms), as well as processing of the granules prior to
deposition [@henryCookingStarch2009; @graneroStarchTaphonomy2020; @haslamDecompositionStarch2004]. 
The potential for detrimental diagenetic effects on starch granules increases as 
the size and amylose content decreases
[@francoStarchDegradation1992; @haslamDecompositionStarch2004]. 
Combined, the effect of intra-oral starch incorporation
and the bias against large granules, together with the increased effect of taphonomy
on  small granules, would eliminate a large portion of the consumed starch granules,
and would explain why the granules extracted from archaeological dental calculus 
are often sparse.

Additionally, the size of the calculus deposit seems to influence the quantity of 
starches extracted from the calculus, as we found a strong positive correlation
between biofilm size and retained starch granules
(Figure \@ref(fig:cor-plot)), which contradicts findings from archaeological contexts
[@wesolowskiEvaluatingMicrofossilContent2010; @dudgeonDietGeographyDrinking2014]. 
When the concentration of starch granules
per mg calculus is considered, the correlation is weaker, but still present
(Figure \@ref(fig:cor-plot2));
while the larger deposits contain a higher absolute count, our findings also suggest
that they contain a slightly higher concentration of starches. 
The lack of a correlation
in archaeological contexts could be due to diagenetic effects; or, the absence of 
amylase activity in our study could be impacting our interpretations.

<!-- How are starch granules trapped in dental calculus? Does anyone actually know? -->

The mechanism by which starch granules are incorporated into plaque and calculus 
remains largely unknown, and few studies have directly investigated potential
mechanisms. We know that a proportion of the starch granules entering 
the mouth can become trapped in the plaque/calculus, and can be recovered from
archaeological samples of significant age 
[@henryNeanderthalCalculus2014; @buckleyDentalCalculusCooking2014; @wuDietEarliest2021]. 
Studies have also shown that not all starch granules come from a dietary source. 
Other pathways include cross-contamination from plant interactions in soil, such 
as palm phytoliths adhering to the skin of sweet potatoes 
[@trompDietaryNondietary2015], 
or accidental ingestion not related to food consumption 
[@radiniFoodMultiplePathways2017; @radiniMedievalWomenEarly2019].

When starch granules enter the mouth, whether through ingestion of food or accidental
intake, they immediately encounter multiple obstacles. It is likely
that the bulk of starch granules are swallowed along with the food, and are 
only briefly retained in the oral cavity. Other granules that are broken off
during mastication may be retained in the dentition. These granules are then
susceptible to mechanical removal by the tongue, salivary clearance, and hydrolysis
by $\alpha$-amylase [@kashketFoodParticles1996].
Starch granules that are trapped in crevices and channels on the surface of the
mineralised plaque would be (at least to some extent) protected from salivary
clearance and mechanical cleaning actions of the tongue and lips. This may explain 
why a previous study found starches more commonly in clusters than dispersed over
the surface of the dental calculus [@powerSEMCalculus2014]. The authors hypothesised 
that the granules are either deposited in clusters, or group together in cracks and
crevices within the mineral matrix. Unmineralised Lacunae and channels within the 
calculus matrix have been shown to contain viable
bacteria, and may also be large enough to contain starch granules. These can 
range from the width of a single cell, to multiple-cell
width [@tanCalculusUltrastructure2004], of which the latter could feasibly contain 
starch granules. 
If this is indeed one of the incorporation mechanisms of starch granules, then the 
limit of incorporated starches is set by the number and size of channels. Since 
this is likely controlled by the size of the calculus deposit, then the number of 
starches will increase as the size of the biofilm increases, which is consistent 
with our results 
(Figures \@ref(fig:cor-plot1) and \@ref(fig:cor-plot2)).
The size bias against large granules (>20 $\mu$m) may give further credence to the 
incorporation pathway of starch granules primarily in cracks and crevices in the 
calculus, as the smaller starch granules have an advantage over larger granules, 
and can be stored in larger quantities.  
While potentially protected against clearance, granules trapped 
in plaque/calculus will still be susceptible to hydrolysis, as $\alpha$-amylase has
the ability to bind to both tooth enamel and bacteria within a biofilm and retain
a portion of its hydrolytic activity
[@nikitkovaStarchBiofilms2013; @tanStudyBacterialViability2004; @tanCalculusUltrastructure2004].
<!-- These channels and pockets of organic matter within the inorganic matrix are used by the 
bacteria for transportation of nutrients, and their persistence in the otherwise 
mineralised matrix may be the result of the differing 
rate of mineralisation displayed by the bacteria [@tanStudyBacterialViability2004].-->
The susceptibility of granules to hydrolysis depends on the crystallinity and size
of the starch granule, as well as the mode of processing. As mentioned previously,
smaller starch granules are more susceptible to enzymatic degradation, as are 
pre-processed starches (e.g. by cooking), while dehydrated starches will have a
reduced susceptibility
[@lingstromStarchyFood1994; @francoStarchDegradation1992; @haslamDecompositionStarch2004; 
@bjorckStarchProcessing1984; @henryCookingStarch2009]. 
<!--
Starches also have the ability to adhere to certain bacteria [@toppingResistantStarch2003],
which would allow starches to attach to bacterial communities within the biofilm.
Following deposition and/or mineralisation events, the granules that are able to 
resist hydrolysis and 
mechanical removal will then be trapped in pockets within the mineral matrix, and
will temporarily be protected from shearing action and salivary 
clearance. -->
This means, that the dietary picture we obtain from starch granules extracted from 
dental calculus reflects a number of individual, dietary, and environmental (both
pre- and post-mortem environments) factors, and that this will likely be a
somewhat random snapshot given the irregularity of plaque mineralisation within
and between individuals [@jinSupragingivalCalculus2002; @jepsenCalculusRemoval2011]. 
Although, certain factors may increase the likelihood of incorporation, such 
as abundance, size, and morphology of granules.

<!-- in summary: we know very little about the mechanism behind how starches 
become trapped in dental calculus, but it would be nice to find out more. -->

<!-- limitations of the platform show which questions would be unanswered -->
This article presents preliminary research exploring the potential of an oral 
biofilm model for dietary research in archaeology. A limitation of this study 
is the absence of amylase in the model. The presence of amylase will likely affect 
the total granule counts as well as the size ratios, as smaller starches may be more 
susceptible to hydrolysis 
[@francoStarchDegradation1992; @haslamDecompositionStarch2004]. 
In future experiments, we recommend the addition of $\alpha$-amylase to the model
in concentrations similar to those found in the oral cavity <!-- provide concentration and citation.--> 
<!-- foreshadowing... -->
While we are able to show the differing 
incorporation caused by absolute counts available, this
was merely a side-effect of the difference in the number of granules in potato and 
wheat solutions of the same concentration (w/v). Further research should test 
multiple differing concentrations of the same starch type.
The use of EDTA may also have affected counts. While previous studies have shown 
negligible morphological changes caused by exposure to EDTA 
[@trompEDTACalculus2017; @lemoyneCalculusPretreatments2021; @modiCalculusMethodologies2020], 
these studies have not considered changes to separate size
categories within starch types, and whether shifts in size ratios occur due to
exposure to the pre-treatment chemicals.
The total number of granules on a slide often exceeded a number that 
was feasible to count in a reasonable time period, so we calculated the total 
counts by extrapolating from three slide transects. 
Thus, we reasonably assume that the three transects are a good representation 
of the entire slide, and that the distribution of all granules on the slide is 
relatively homogenous.   
Finally, we only used native starches in the experimental procedure and the results 
will likely differ for processed starches [@graneroStarchTaphonomy2020]. 
Based on counts obtained by Leonard
and colleagues [-@leonardDentalCalculus2015, Supplement 2], processing and amylase
may have a substantial effect on starch granule retention in the oral cavity.

<!-- How this engineering will facilitate future research -->
The oral biofilm model described in this study, and in 
Bartholdy and colleagues (in prep.),<!-- insert citation --> provides a method to directly
explore the incorporation and extraction of dietary compounds from dental calculus 
in a controlled laboratory setting. The addition of known species in separate
samples also removes the identification bias against the smaller undiagnostic starches.<!-- rephrase -->
It can also address the call for more baseline testing of biases associated with 
dietary research conducted on dental calculus 
[@lemoyneCalculusPretreatments2021].
<!-- How it will facilitate the specific topic of research (e.g. archaeology) -->
*In vivo* studies on humans and non-human primates will be limited by the variability 
occurring
between individuals, and difficulties documenting the entirety of starch granules
entering the oral cavity at any given moment, especially accidental intake. 
Our experimental setup allows us a
higher degree of control over the factors that influence starch incorporation, such as
dietary intake, processing of starches leading to differential survivability, 
and inter- and intra-individual variation in plaque accumulation and 
mineralisation.
The latter is especially difficult to control *in vivo* as it is influenced by 
numerous factors including genetics, diet, and tooth morphology [@jepsenCalculusRemoval2011]<!-- more citations -->.  
Further research is necessary to explore the mechanisms of the intra-oral starch 
incorporation and retention in dental calculus, and the dental calculus model
presented in this study is uniquely suited to explore these questions and 
may improve interpretations of dietary research in past populations.
<!-- still need to replicate results and do more science, but pretty cool, right? -->

# Conclusions

Our preliminary study shows that a very small proportion of the ingested starch
granules are retained in a dental calculus model.

Calculus has a low capacity for retention of starch granules, and this effect is
compounded by diagenetic effects in archaeological remains, resulting in low overall
counts of extracted granules. Additionally, the size of granules will influence the 
likelihood of incorporation, as large starches have a decreased incorporation, medium
starches increased, and small starches the only representative of intake.

Given the direct proportional incorporation of starches with quantity of exposure<!-- rephrase -->, 
we can say that the proportion of starches consumed will in many cases be reflected 
in the quantity
of starches extracted from the dental calculus, at least in modern calculus samples
unaffected by diagenesis.
Whether or not this also applies to archaeological samples remains to be tested.

The size of calculus deposit also influences the maximum capacity of granule incorporation; as the size of the deposit increases, so does the absolute count of
incorporated granules.


The data from this study are not sufficient to confirm or deny any proposed methods
of starch incorporation; however, while we are unable to address the mechanism(s) of
starch incorporation with the current experimental setup, this is something that can
potentially be addressed with the calculus model presented in this paper.

<!-- Forward-looking statements about the field as a whole -->
While we have shown multiple factors that influence the likelihood 
of incorporation, it seems the process is somewhat stochastic, and possibly related 
to the biofilm mineralisation events (as discussed above), which are irregular and
related to various factors<!-- citation needed -->. 
This means that the dietary components extracted from dental calculus provide a 
snapshot of the diet around the time of the mineralisation event, which may not 
be an accurate picture of the diet as a whole.

The dental calculus biofilm model presented in this study is a powerful tool to 
investigate various aspects
of dietary research.
