# Introduction

<!-- basic introduction to the field, comprehensible to a scientist in any discipline -->
<!-- Dental calculus is mineralised plaque. And it is pretty cool. -->
Dental calculus, mineralised dental plaque, has proven to contain a wealth of 
dietary information in the form of plant microfossils 
[@henryCalculusSyria2008; @hardyStarchGranulesDental2009], 
proteins [@hendyProteomicCalculus2018; @warinnerDirectEvidenceMilk2014],
and other organic residues [@buckleyDentalCalculusCooking2014]. 
It has also proven to be able to retain and preserve dietary information for millenea,
providing detailed dietary information on past populations 
[@henryCalculusSyria2008; @jovanovicNeolithicCalculus2021; @taoWheatCalculus2020] 
and species [@henryNeanderthalCalculus2014; @hardyNeanderthalMedics2012]. 

<!-- more detailed background, comprehensible to scientists in related disciplines -->

Until recently, few studies directly investigated the presence of plant microremains
in the dental calculus of archaeological remains. The ability to extract phytoliths
from the dental calculus of archaeological fauna to investigate diet was first 
noted by Armitage [-@armitageExtractionIdentificationOpal1975], 
and later by Middleton and Rovner [-@middletonExtractionOpalPhytoliths1994],
and Fox and colleagues [-@foxPhytolithCalculus1996]. The ability to detect coca
consumption by looking at human dental calculus was explored by Klepinger and Kuhn
[-@klepingerCalculusCoca1977], and starches and phytoliths were extracted from 
human dental calculus by Cummings and Magennis [-@cummingsMayanCalculus1997].

In more recent years, the study of dental calculus has increased exponentially, 
and the wealth of information contained within the mineralised matrix has been, 
to a larger extent, acknowledged. The applications of dental calculus span a wide
variety of archaeological research areas, such as oral microbiome 
characterisation (including pathogens) through the analysis of DNA and proteins 
[@adlerSequencingAncientCalcified2013; @warinnerPathogensHostImmunity2014],
microbotanical remains [@henryCalculusSyria2008; @hardyStarchGranulesDental2009;
@mickleburghNewInsightsConsumption2012], 
other organic residues and proteins from dietary compounds 
[@buckleyDentalCalculusCooking2014; @hendyProteomicCalculus2018], 
and nicotine-use [@eerkensDentalCalculusSource2018]. Especially the extraction 
of starch granules has become a rich source of dietary
information, as starch granules have proven to preserve well within dental calculus
over a variety of geographical and temporal ranges 
[@pipernoStarchGrains2008; @henryNeanderthalCalculus2014; @taoWheatCalculus2020;
@jovanovicNeolithicCalculus2021].

<!-- starches from dental calculus -->
Despite this, our knowledge of dental calculus and the incorporation pathways of 
the various markers is limited [@radiniFoodMultiplePathways2017], as is our 
knowledge of information-loss caused by these pathways and the methods we use to 
extract and analyse dental calculus and make inferences on past diets. 
Extraction methods were tested 
by Tromp and colleagues [-@trompEDTACalculus2017], specifically regarding
decalcification using HCl or EDTA. 
The authors found significantly more starches with the EDTA extraction method 
than the HCl extraction method; however, as noted by the authors, comparisons 
involving archaeological calculus are problematic due to variability between and 
within individuals. Other studies have been conducted on modern populations 
[@leonardDentalCalculus2015] and primates [@powerChimpCalculus2015], both with
well-documented dietary intake, to reconcile our interpretations on the recovery 
of microremains (both phytoliths and starches) from dental calculus and how well
they represent actual dietary intake. These studies are justifiably limited, 
despite meticulous documentation and observation, due to unknown variables and 
uncertainty involved when studying living organisms. Dental calculus is a complex 
oral biofilm with a
multifactorial aetiology and variable formation rates both within and between
individuals [@jepsenCalculusRemoval2011].
Additionally, the effects of the many different methods
of starch processing, as well as post-depositional processes, are still being 
explored [@graneroStarchTaphonomy2020].

<!-- clearly stating the general problem being addressed by this particular study -->
<!-- Dental calculus research has its limitations, all of which I will solve with this
single method. -->
In this exploratory study, we use an oral biofilm model to investigate the 
retention of starch granules within dental calculus, in a controlled laboratory 
setting. Our main questions concern the representation of granules extracted
from the calculus compared to the actual intake. How much of the original diet is 
incorporated into the calculus, and how much is recovered? 
Is there differential loss of information from specific dietary markers that affects 
the obtained dietary information, and how does this affect the representation of diet from
extracted microremains? We find that a limited proportion of the starch input is actually 
retained in the calculus, as well as a shift in the size ratios of individual starch granules
that are incoporated into the calculus. We also show that the number of starch
granules that are incorporated increases as the size of the calculus deposit 
increases.
